# Generated by Django 4.2 on 2023-04-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
